import NextHead from 'next/head'

export default function Head() {
  return (
    <NextHead>
      <title>ADesign</title>
      <meta name='description' content='Generated by create next app' />
      {/* <link rel='icon' href='/favicon.ico' /> */}
    </NextHead>
  )
}
