import NextHead from 'next/head'

export default function Head() {
  return (
    <NextHead>
      <title>AMAgency</title>
      <meta name='description' content='Generated by create next app' />
      {/* <link: */}
      <link rel="icon" href="/favicon.png" />
    </NextHead>
  )
}
